# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat_position',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='place',
            name='long_position',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
