# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171107_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'user_not_been'), (1, 'user_been')], default=0),
        ),
    ]
